#pragma config(UART_Usage, UART1, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in3,    leftIRSensor,   sensorAnalog)
#pragma config(Sensor, in2,    rightIRSensor,  sensorAnalog)
#pragma config(Sensor, in1,    topIRSensor,    sensorAnalog)
#pragma config(Sensor, in4,    backIRSensor,   sensorAnalog)
#pragma config(Sensor, in5,    back_limit_1,    sensorAnalog)
#pragma config(Sensor, in6,    back_limit_2,   sensorAnalog)
#pragma config(Sensor, dgtl1,  Power_Switch,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  leftWheelSensor, sensorDigitalIn)
#pragma config(Sensor, dgtl3,  rightWheelSensor, sensorDigitalIn)
#pragma config(Sensor, dgtl4,  ball_limit_switch, sensorDigitalIn)
#pragma config(Sensor, dgtl6,  leftLF,         sensorDigitalIn)
#pragma config(Sensor, dgtl7,  rightLF,        sensorDigitalIn)
#pragma config(Sensor, dgtl8,  compass_LSB,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  compass_Bit3,   sensorDigitalIn)
#pragma config(Sensor, dgtl10, compass_Bit2,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, compass_MSB,    sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           roller,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BNSlib_HC05.h"
#include "var_updated.c"
#include "encoder_updated.c"

task main(){
	//Initialise variables and start multi-tasking for encoder tasks
	initialise();
	setBaudRate(UART1, baudRate9600);
	startTask(counting);
	startTask(mapping);

	while(true){
		writeDebugStreamLine("Battery: %d",nAvgBatteryLevel);

		while (SensorValue(Power_Switch) == Power_Switch_ON && ball_caught == 0 && boundary_avoidance()){
			//main code here:

			if (phase%2 == 1){
				//bnsSerialSend(UART1, "Move straight 1 start..\n");
				if (move_straight(60)==0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				//bnsSerialSend(UART1, "Pan 1 start..\n");
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if(phase==1){
					if (pan_to_heading(90) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				else {
					if (pan_to_heading(270) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				//bnsSerialSend(UART1, "Move straight 2 start..\n");
				if (move_straight(60)==0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				//bnsSerialSend(UART1, "Pan 2 start..\n");
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if(phase==1){
					if (pan_to_heading(90) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
					sleep(500);
				}
				else {
					if (pan_to_heading(270) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
					sleep(500);
				}
				//bnsSerialSend(UART1, "Move straight 3 start..\n");
				if (move_straight(60)==0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				//bnsSerialSend(UART1, "Pan 3 start..\n");
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if(phase==1){
					if (pan_to_heading(90) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				else {
					if (pan_to_heading(270) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
			}

			else if (phase%2 == 0){
				//bnsSerialSend(UART1, "Pan start..\n");
				if (pan_by_degree(90, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if(phase==2){
					if (pan_to_heading(0) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				else {
					if (pan_to_heading(180) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				//bnsSerialSend(UART1, "Move straight start..\n");
				if (move_straight(60)==0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				//bnsSerialSend(UART1, "Pan start..\n");
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if (pan_and_search(180, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if (pan_by_degree(90, 'r') == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				sleep(500);
				if(phase==2){
					if (pan_to_heading(270) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
				else {
					if (pan_to_heading(90) == 0 || SensorValue(Power_Switch) == Power_Switch_OFF) break;
				}
			}

			//if (phase == 1){
			//	bnsSerialSend(UART1, "Phase 1 End..\n");
			//	bnsSerialSend(UART1, "PHASE 2 ------------------\n");
			//}
			//if (phase == 2){
			//	bnsSerialSend(UART1, "Phase 2 End..\n");
			//	bnsSerialSend(UART1, "PHASE 3 ------------------\n");
			//}
			//if (phase == 3){
			//	bnsSerialSend(UART1, "Phase 3 End..\n");
			//	bnsSerialSend(UART1, "PHASE 4 ------------------\n");
			//}
			//if (phase == 4){
			//	bnsSerialSend(UART1, "Phase 4 End..\n");
			//	bnsSerialSend(UART1, "PHASE 1 ------------------\n");
			//}
			phase+=1;
			if (phase == 5){
				phase = 1;
			}
		}
		//If power is off, stop all motors and reinitalise variables
		if(SensorValue(Power_Switch) == Power_Switch_OFF){
			moveMotor(0,0,'f',0);
			motor(roller)=0;
			motor(servo)=-85;
			initialise();
			//print_bluetooth(2,0);
		}
	}
}
